export const INCREMENT_REDUCER = "INCREMENT_REDUCER";
export const DECREMENT_REDUCER = "DECREMENT_REDUCER";

export const GET_METHODE = "GET_METHOD"
export const ADD_METHODE = "ADD_METHOD"
export const UPDATE_METHODE = "UPDATE_METHOD"
export const DELETE_METHODE = "DELETE_METHOD"